# Generated by Django 3.2.12 on 2022-04-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsite220', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutschool',
            options={'verbose_name': 'aboutschool', 'verbose_name_plural': 'aboutschools'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='managements',
            options={'verbose_name': 'management', 'verbose_name_plural': 'managements'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'staff', 'verbose_name_plural': 'staff'},
        ),
    ]
