# Generated by Django 3.2.12 on 2022-04-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsite220', '0002_auto_20220405_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(upload_to='banner')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutschool',
            options={'verbose_name': 'aboutschool', 'verbose_name_plural': 'aboutchools'},
        ),
    ]
