# Generated by Django 3.2.12 on 2022-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsite220', '0003_auto_20220405_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science', models.PositiveIntegerField(blank=True, max_length=50, null=True)),
                ('students', models.PositiveIntegerField(blank=True, max_length=50, null=True)),
                ('teachers', models.PositiveIntegerField(blank=True, max_length=50, null=True)),
                ('classroom', models.PositiveIntegerField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'statistics',
                'verbose_name_plural': 'statistic',
            },
        ),
    ]
