# Generated by Django 3.2.12 on 2022-04-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsite220', '0006_features'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
    ]
