# Generated by Django 3.2.12 on 2022-04-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsite220', '0008_features'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
