# Generated by Django 3.2.12 on 2022-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsite220', '0012_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='managements',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
