# Generated by Django 3.2.12 on 2022-04-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsite220', '0018_auto_20220413_0127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
