# Generated by Django 3.2 on 2021-05-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sizemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.ManyToManyField(related_name='products', to='products.SizeModel'),
        ),
    ]
